export const data2 = {
    "Sky Park": {
        "title": "Sky Park",
        "description": "Крупнейший крытый парк в Кыргызстане",
        "areatitle": "Общая площадь помещения парка:",
        "areatext": [
            "5500 кв. м. Высота самой высокой горки составляет - 13 м,протяженностью - 52 м.",
            "Зиплайн располагается На высоте - 13 м.",],
        "about": "Центр развлечений «Sky Park» успешно осуществляет свою работу С 2018 года.",
        "zonestitle": "Дополнительные зоны:",
        "zones": "Зона фуд-корта, магазин игрушек, анимэ-магазин, тир, Зоопарк и многое другое.",
        "attractions": [
            "- Зиплайн,",
            "- Желтая горка и синяя горка (высота 12 метров, длина 47 метров)",
            "- Большой бассейн с шариками",
            "-Мини-соты",
            "-Скалодром",
            " - Сетчатый лабиринт",
        ],
        "gamecomplex": [
            "- Батут для маленьких детей",
            "- Вулкан",
            "- Гимнастический батут",
            "- Карусели - Песочница",
            "- Игрушечный самолет",
            "- Зона творчества",
            "- Игровые панели",
            "- Автодром",
            "- Настольные игры",
            "- Виар зона",
            "- Тир",
        ],
        "imgFirstSection": [
            "../assets/skypark/first/img01.webp",
            "../assets/skypark/first/img02.webp",
            "../assets/skypark/first/img03.webp",
            "../assets/skypark/first/img04.webp",
            "../assets/skypark/first/img05.webp",
            "../assets/skypark/first/img06.webp",
            "../assets/skypark/first/img07.webp",
        ],
        "imgPortfolio": [
            "../assets/skypark/second/img01.webp",
            "../assets/skypark/second/img02.webp",
            "../assets/skypark/second/img03.webp",
            "../assets/skypark/second/img04.webp",
            "../assets/skypark/second/img05.webp",
            "../assets/skypark/second/img06.webp",
            "../assets/skypark/second/img07.webp",
            "../assets/skypark/second/img08.webp",
            "../assets/skypark/second/img09.webp",
            "../assets/skypark/second/img10.webp",
            "../assets/skypark/second/img11.webp",
            "../assets/skypark/second/img12.webp",
            "../assets/skypark/second/img13.webp",
            "../assets/skypark/second/img14.webp",
            "../assets/skypark/second/img15.webp",
            "../assets/skypark/second/img16.webp",
            "../assets/skypark/second/img17.webp",
            "../assets/skypark/second/img18.webp",
            "../assets/skypark/second/img19.webp",
            "../assets/skypark/second/img20.webp",
            "../assets/skypark/second/img21.webp",
            "../assets/skypark/second/img22.webp",
        ],
        "price": ["490","690"]
    },
    "Smagic Techno": {
        "title": "Smagic Технопарк",
        "description": "Общая площадь помещения парка: 5500 кв. м.",
        "areatitle": "Общая площадь помещения парка:",
        "areatext": [
            "6878 кв. м.",],
        "about": "Центр развлечений «Smagic ТехноПарк» успешно осуществляет свою работу С 2019 года.",
        "zonestitle": "Дополнительные зоны:",
        "zones": "Город Профессий и Город Активити. На территории развлекательной зоны имеется :тир, магазин игрушек,фуд-корт,салон",
        "attractions": [
            "- 2 Вида горок,",
            "- 2 зоны с шариками",
            "- Тюбинговая горка",
            " - Скалодром",
            "- Зиплайн",
            " - Соты",
            " - Сетчатый лабиринт",
            " - Вуклан",
            " - Батут",
        ],
        "gamecomplex": [
            "- Автодром",
            "- Песочница",
            "- 2 вида качелей",
            "- Зона творчества",
            "- Рыбалка",
            "- Лего большое и маленькое",
            "- Настольные игры",
        ],
        "imgFirstSection": [
            "../assets/techno/first/img01.jpg",
            "../assets/techno/first/img02.jpg",
            "../assets/techno/first/img03.jpg",
            "../assets/techno/first/img04.jpg",
            "../assets/techno/first/img05.jpg",
        ],
        "imgPortfolio": [
            "../assets/techno/second/img01.jpg",
            "../assets/techno/second/img02.jpg",
            "../assets/techno/second/img03.jpg",
            "../assets/techno/second/img04.jpg",
            "../assets/techno/second/img05.jpg",
        ],
        "price": ["350","690"],
    },
    "Smagic Tsum": {
        "title": "Smagic Цум 2",
        "description": "Общая площадь помещения парка: 5500 кв. м.",
        "areatitle": "Общая площадь помещения парка:",
        "areatext": [
            "2300 кв. м. Вместимость : 600 человек"],
        "about": "Центр развлечений «Smagic ЦУМ2» успешно осуществляет свою работу С 2019 года.",
        "zonestitle": "Дополнительные зоны:",
        "zones": "Зона фуд-корта, магазин игрушек, тир,многое другое.",
        "attractions": [
            "-Скалодром,",
            "- Соты",
            "- Бассейн с шариками",
            "- Батут",
            "- Крутые горки",
            " - Лабиринт",
            " - Кинетический песок",
            " - Магнитный конструктор",
        ],
        "gamecomplex": [
            "- Лего и мини лего",
            "- Мягкий конструктор",
            "- Вулкан",
            "- Зона рукоделия",
            "- 2 вида рыбалки",
            "- Настольные игры(хоккей и аэро-хоккей",
            "- Автодром",
        ],
        "imgFirstSection": [
            "../assets/tsum/first/img01.jpg",
            "../assets/tsum/first/img02.jpg",
            "../assets/tsum/first/img03.jpg",
            "../assets/tsum/first/img04.jpg",
            "../assets/tsum/first/img05.jpg",
        ],
        "imgPortfolio": [
            "../assets/tsum/second/img01.jpg",
            "../assets/tsum/second/img02.jpg",
            "../assets/tsum/second/img03.jpg",
            "../assets/tsum/second/img04.jpg",
            "../assets/tsum/second/img05.jpg",
        ],
        "price": ["420","600"],
    },
    "Smagic Tommi": {
        "title": "Smagic Tommi mall",
        "description": "Общая площадь помещения парка: 5500 кв. м.",
        "areatitle": "Общая площадь помещения парка:",
        "areatext": [
            "778 кв. м. Вместимость : 200 человек"],
        "about": "Центр развлечений «Smagic Tommi Mall» успешно осуществляет свою работу С 2021 года.",
        "zonestitle": "Дополнительные зоны:",
        "zones": "Зона фуд-корта, магазин игрушек, тир.",
        "attractions": [

            "- Спортивный батут",
            "- Классический батут",
            "- Мини зиплайн",
            " - Сетчатый лабиринт",
            " - Бассейн с шариками",
        ],
        "gamecomplex": [
            "- Большая зона Лего",
            "- Песочница",
            "- Мини-скалодром",
            "- Горки",
            "- Автодром",
            "- Зона творчества",
            "- Игровые панели",
            "- Автодром",

        ],
        "imgFirstSection": [
            "../assets/tommi/first/img01.jpg",
            "../assets/tommi/first/img02.jpg",
            "../assets/tommi/first/img03.jpg",
            "../assets/tommi/first/img04.jpg",
            "../assets/tommi/first/img05.jpg",

        ],
        "imgPortfolio": [
            "../assets/tommi/second/img01.jpg",
            "../assets/tommi/second/img02.jpg",
            "../assets/tommi/second/img03.jpg",
            "../assets/tommi/second/img04.jpg",
            "../assets/tommi/second/img05.jpg",
        ],
        "price": ["300","420"],
    },
}
export default data2